//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public int Id { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<double> Score { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SubjectMarkComponentId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual RealSemester RealSemester { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject_MarkComponent Subject_MarkComponent { get; set; }
    }
}
